@API_URL = http://localhost:5000
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZGMwOWQ2Y2E5ZDBlOTk3N2E1ZTNiYiIsImlhdCI6MTY1ODU4OTA2NCwiZXhwIjoxNjU5MTkzODY0fQ.-79k4sVS_rXTFsG6VsKBBA9S_Cf0Ih19xFbdqgmVy90

### home
GET {{API_URL}}/

### all
GET {{API_URL}}/api/auth

### create / register
POST {{API_URL}}/api/auth/register
Content-Type: application/json

{
    "name": "iman",
    "email": "iman@gmail.com",
    "password": "iman"
}

### login
POST {{API_URL}}/api/auth/login
Content-Type: application/json

{
    "email": "iman@gmail.com",
    "password": "iman" 
}